### PR TITLE
Feature/give update donor information post create filter

### PR DESCRIPTION
**Pull request by andrewminion-luminfire**
## Description
Adds a filter to modify the `$donor` object after retrieving/creating it.

Use case: we’re building a plugin to add matching donations and the match donations should not be credited to the original donor.

## How Has This Been Tested?
Tested on a local WordPress installation.

## Types of changes

New feature: adds a new filter

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by andrewminion-luminfire** [comment]
After writing this, I thought of perhaps a cleaner way of accomplishing the same thing for my use case and submitted PR https://github.com/impress-org/give/pull/4017.

**Comment by nciske** [comment]
@mathetos / @DevinWalker 

We'd appreciate if ya'll could give this some attention so we don't have to write an iffy workaround in our plugin. Thanks!

**Comment by nciske** [comment]
Or this alternative: https://github.com/impress-org/give/pull/4017

**Comment by kevinwhoffman** [comment]
Closing. See https://github.com/impress-org/give/pull/4017#issuecomment-470595748 for rationale.

**Pull request closed without merging**
