### PR TITLE
fix: improve block styling and usability #3887

### LINKED ISSUE #3887: fix: improve block styling and usability
# Bug Report

## User Story

As a WordPress 5.0 user, I want Give blocks to function without error and reflect the appearance of their front end counterparts so that the editor represents an accurate preview of the end result.

## Current Behavior

The following unresolved issues with Gutenberg:

- Form block: PHP notices appear when a form block is inserted due to a lack of default attribute values.
- Form block: There is no bottom margin between the form select box and button.
- Form block: Tooltip icons appear in italics.
- Form block: Hover controls overflow outside the block.
- Form block: "Edit Form" hover control should remain white, instead of turning black, when hovered.
- Form block: Clicking "Edit Form" redirects to the WP login screen, not the form editor.
- Form block: Content does not render
- Form block: radio buttons are squished due to block component styles
- Form Grid block: The presence of this blocks breaks front-end content, prevents the donation form block from rendering correctly, and does not render anything within the grid.
- Donor Wall block: Toggling the "Donor with Comment" option causes the block to refresh but it never stops spinning until the setting is disabled.

## Expected Behavior

The above issues have been resolved. The blocks render without error and accurately reflect their appearance on the front end.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install Give 2.3.0
2. Install WordPress 5.0 RC3 using the Beta Tester plugin with bleeding nightlies enabled
3. Create a Give form with goal and content
4. Create a few more forms
5. Create some test donations
6. Create new page and insert the Give blocks
7. Adjust the block settings and preview on front end to verify they appear as expected

## Related

- https://github.com/impress-org/give/issues/3813

## Acceptance Criteria

- [x] Blocks can be placed and saved without causing PHP notices.
- [x] A bottom margin has been added to the form select control.
- [x] Tooltips do not appear in italics.
- [x] Hover controls do not overflow outside of the block.
- [x] Radio buttons within a form are not squished.
- [x] "Edit Form" remains white when hovered.
- [x] Clicking "Edit Form" takes the user to the form editor, not the WP login screen.
- [x] The Form block does not spin upon initialization.
- [x] Form content renders when the block setting is enabled (be sure to add content to form first).
- [x] The Form Grid block renders on the front end without breaking other blocks.
- [x] The Donor Wall block's "Donor with Comment" does not cause the block to load endlessly.
- [x] After Clicking on Edit Form Once the "Edit Form" button will need to remain white.

### PR DESCRIPTION
**Pull request by kevinwhoffman**
## Description

Resolves #3887 by fixing styling conflicts and improving block usability.

Work in progress... see acceptance criteria for current status.

### CODE REVIEW

**Comment by kevinwhoffman** [comment]
@ravinderk Please pick up where I left off on this branch and resolve the remaining acceptance criteria in #3887.

Here's a screencast demonstrating the current issues with the Form block's content setting: https://www.useloom.com/share/5840e56b18684282ad02879ffba0f35a

**Comment by ravinderk** [comment]
@kevinwhoffman Can you explain `The Form block does not spin upon initialization.` from `Acceptance Criteria`.

Rest I fixed. please review it when you have time. I will continue testing tomorrow.

**Comment by ravinderk** [comment]
@kevinwhoffman I fixed most of Gutenberg related issue, please review this PR and fix if any styling issue still left.

**Comment by ravinderk** [comment]
@kevinwhoffman issue has been fixed which discussed here: https://givewp.slack.com/archives/C0FAGC83C/p1544587840044900

**Comment by kevinwhoffman** [comment]
@ravinderk I'm seeing two different blank slate experiences when the form grid block is inserted without forms:

1. I would like to see this blank slate whenever there are no forms.

image


2. However I often see this version instead with a giant logo and no button. Try inserting the form grid block, then deleting it, and inserting it again to trigger this version.

image

Can you make sure the first version is always used when there are no forms?

**Comment by ravinderk** [comment]
@kevinwhoffman First blank template comes from: `blocks/components/no-form/index.js` second comes from `Give_Donor_Wall_Block::blank_slate`. If we want the same blank slate then we have to create a custom component which will extend `ServerSideRender`.

**Pull request merged**
