### PR TITLE
fix: use the custom table to render form list table using wp_list_table

### LINKED ISSUE #3845: feat: add search bar to Donation Forms screen
# Feature Request

## User Story

As a user, I want a search bar on the Donation Forms screen so that it I have more control over searching for forms like I do with donations and donors.

## Visuals

image

## Possible Solution

Use the same search bar UI from the Donations screen, but make sure the behavior reflects the acceptance criteria below.

The `Forms` dropdown should contain the following options:

- Any Goal Status
- Goal Achieved
- Goal In Progress
- Goal Not Set

## Acceptance Criteria

- [x] The old search box in the upper right has been removed.
- [x] When a string is entered into search, only forms whose names or IDs that contain that string are displayed.
- [x] When start and end dates are provided, only forms published between those dates are displayed.
- [x] When only a start date is provided, it shows all forms created after that date.
- [x] When only an end date is provided, it shows all forms created before that date.
- [x] When `Any Goal Status` is selected, all forms are displayed.
- [x] When `Goal Achieved` is selected, only forms with completed goals are displayed.
- [x] When `Goal In Progress` is selected, only forms with incomplete goals are displayed.
- [x] When `Goal Not Set` is selected, only forms without goals are displayed.
- [x] The date filters work with a non-default date format in WP settings.
- [x] Each field label is aligned vertically with its respective input.
- [x] Use the custom table to render form list table (`WP_LIst_Table`).

### PR DESCRIPTION
**Pull request by kakshak**
## Description
This PR will fix #3845 

## How Has This Been Tested?
Manually tested.

## Screenshot
image

## Types of changes
Bug fix (a non-breaking change which fixes an issue)

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by kakshak** [comment]
@ravinderk As per our discussion on call I've created the PR for listing the table using `WP_List_Table` based on the this [example URL](woocommerce/woocommerce:includes/admin/class-wc-admin-post-types.php@242641e#L76). Please review that and do needful for advanced search functionality.

**Comment by kevinwhoffman** [comment]
@ravinderk I began reviewing this and see that each filter bar on Forms, Donations, and Donors is using it's own CSS despite the fact that the UI in each bar contains the same components. There are styling issues across all 3 bars that should be addressed. I will come back to this closer to 2.4.0 release and refactor the CSS to be the same across all 3 screens.

**Comment by kevinwhoffman** [comment]
@DevinWalker will review this one prior to 2.4.0 launch and decide if it's ready.

**Comment by DevinWalker** [comment]
I have updated this PR with the following fixes:

1. Simplified CSS so the filter bar is more responsive now using better positioning rules.
2. Matched the padding and margins of other filter bars for better cross screen consistency 
3. Simplified `give_form_search_query_filter()` and resolved issue with `goal_not_set` filter not properly checking in `_give_goal_option` does exists. 
4. Resolved PHP notice when unnecessarily checking `$_GET['give-forms-goal-filter']` is empty without checking `isset()`.

**Pull request merged**
